name: Update supporters
run-name: ${{ github.actor }} is deploying to GH pages 🚀
on:
  issues:
    types: [opened]

jobs:
  extract-date:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job triggered by a ${{ github.event_name }} event is running on ${{ runner.os }} for branch ${{ github.ref }}"
      - name: Parse issue
        env:
          EVENT_ISSUE_NUMBER: ${{ github.event.issue.number }}
          EVENT_ISSUE_TITLE: ${{ github.event.issue.title }}
          EVENT_USER_LOGIN: ${{ github.event.issue.user.login }}
          EVENT_USER_EMAIL: ${{ github.event.issue.user.email }}
          EVENT_USER_NAME: ${{ github.event.issue.user.name }}
          EVENT_USER_AVATAR: ${{ github.event.issue.user.avatar_url }}
        run: echo "payload ${{github.event.issue}}"
        