name: Update supporters
run-name: ${{ github.actor }} is handling new issue 🚀
on:
  issues:
    types: [opened]

jobs:
  handle-issue:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job triggered by a ${{ github.event_name }} event is running on ${{ runner.os }} for branch ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Update data
        env:
          EVENT_ISSUE_TITLE: ${{ github.event.issue.title }}
          EVENT_USER_LOGIN: ${{ github.event.issue.user.login }}
          EVENT_USER_AVATAR: ${{ github.event.issue.user.avatar_url }}
          EVENT_USER_URL: ${{ github.event.issue.user.url }}
        run : python update.py
      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email github-actions@github.com

      - name: Commit/Push Changes
        run: |
          git add *
          git commit -m "Update data" | exit 0
          git push
      - name: Close Issue
        uses: peter-evans/close-issue@v1
        with:
          issue-number: ${{ github.event.issue.number }}